### ISSUE TITLE
Molteo

### ISSUE THREAD

**Issue by Molteo** [gtalarico/aec-startups#17]
# Title
**Molteo is a cloud platform that makes managing construction projects look easy.**

# Description
Molteo is the cloud software for efficient building with overview. From now on, construction companies can control and optimize everyday work processes in the office easy via the PC and on the construction site quickly via a mobile phone, laptop or tablet.

Molteo provides an easy-to-use tool which provides a real-time overview of projects and construction sites, flexible resource capture, and paperless billing.

Functions: • Personnel planning • Time registration • Calculation • Project management • Payroll • Equipment and material recording • Construction Diary

_ps. Product is available in English, Website coming soon._

# Website
https://molteo.de/

# Image
![Molteo](https://user-images.githubusercontent.com/50488062/57527623-716b6980-7330-11e9-8b14-5236bae06d29.png)

# Crunchbase
https://www.crunchbase.com/organization/molteo

# Industries
* engineering
* construction

Tags:
* Web app
* iOS
* Android
* Analysis 
* Construction Management 
* Cost Estimation Data Management 
* Documentation 
* Cloud
* Project Management

**Comment by gtalarico** [comment]
Uhhh nice. Thank you
