### ISSUE TITLE
Acculis

### ISSUE THREAD

**Issue by visualizor** [gtalarico/aec-startups#28]
# Title
Acculis

# Description
BIM coordination platform

# Website
https://www.acculistech.com/

# Image
None

# Crunchbase
https://www.crunchbase.com/organization/acculis#section-investors

# Industries
* engineering
* architecture

Tags:
* web-app

**Comment by gtalarico** [comment]
Add Entry through https://airtable.com/shrLpxcEdauXQcecZ

**Comment by gtalarico** [comment]
Thanks will review
