### ISSUE TITLE
Add Avail 

### ISSUE THREAD

**Issue by jmclifton** [gtalarico/aec-startups#30]
# Title
AVAIL

# Description
AVAIL’s content management system enables project teams and enterprises to intuitively find, organize, and manage all of their digital assets. AVAIL is designed to work with existing file systems including cloud-based assets, is file agnostic and allows varying levels of user permissions. Faceted content is visually explored and accessed in the context of the design or building information modeling tools. 

# Website
getavail.com

# Image
![Avail_Logo_300x300](https://user-images.githubusercontent.com/6482971/58132936-9b564300-7bf0-11e9-8201-47e3c75bfcc5.png)

# Industries
* architecture, engineering, construction, owner/operators

Tags:
* desktop, browser integrations, analytics, metadata index and search

**Comment by gtalarico** [comment]
Thanks
