### ISSUE TITLE
Add ALICE

### ISSUE THREAD

**Issue by riteshredkar** [gtalarico/aec-startups#38]
# Title
ALICE Technologies

# Description
ALICE leverages AI to speed up the planning process, reduce project schedules, and resolve schedule delays.

# Website
https://alicetechnologies.com/

# Image
https://cdn-images-1.medium.com/max/2600/1*Fbt7LP_0jNF13tdzedwZaA.png

# Crunchbase
https://www.crunchbase.com/organization/alice-technologies

# Industries
* Engineering
* Construction

Tags:
* web-app
* AI

**Comment by gtalarico** [comment]
Thanks!

**Comment by alssica** [comment]
entered into airtable
