### ISSUE TITLE
New tag for AEC start ups

### ISSUE THREAD

**Issue by juliavalentine** [gtalarico/aec-startups#46]
Need new tag of "AI" for AEC startups

**Comment by gtalarico** [comment]
There is a `Claims AI` tag. I added a `Verified AI`. Which one would you like to apply it to?

**Comment by juliavalentine** [comment]
Thanks! I wanted to add it to our company, Kreo, as that's our
differentiation. I just submitted our company to the list, not sure if it's
up yet.

Many thanks,
Julia

**Comment by gtalarico** [comment]
added

**Comment by juliavalentine** [comment]
Thanks!
