### ISSUE TITLE
Field for Location/HQ

### ISSUE THREAD

**Issue by m-clare** [gtalarico/aec-startups#48]
Could a field be added in the airtable to locate offices/HQ for each startup?

**Comment by gtalarico** [comment]
Yes, good idea. 
Would you be willing to help fill out some of the values?

**Comment by m-clare** [comment]
Sure, I'd be happy to.

**Comment by m-clare** [comment]
See attached for an xlsx 
[aec-startups.xlsx](https://github.com/gtalarico/aec-startups/files/3342101/aec-startups.xlsx)
with headquarter information. Hoping you can directly merge this into the airtable.

**Comment by m-clare** [comment]
See attached for an xlsx with added HQ field. I hope you can easily import directly to the airtable (the csv I downloaded is only a few days old).

[aec-startups.xlsx](https://github.com/gtalarico/aec-startups/files/3342110/aec-startups.xlsx)

**Comment by gtalarico** [comment]
Thanks for your help with this!
