### ISSUE TITLE
502 Error: API is required to connect to Airtable

### ISSUE THREAD

**Issue by ahadsheriff** [gtalarico/aec-startups#61]
When using my own AIRTABLE_API_KEY, AIRTABLE_API_URL, and base id and disabling the mock response, I am getting a 502 error:

<img width="1433" alt="Screenshot 2020-05-17 16 03 10" src="https://user-images.githubusercontent.com/5421262/82162336-8ee2e580-9858-11ea-8422-d53e951dc131.png">

<img width="1455" alt="Screenshot 2020-05-17 16 04 20" src="https://user-images.githubusercontent.com/5421262/82162343-9609f380-9858-11ea-8d53-fa4f193a9842.png">

Any ideas as to why this is happening and how I can fix the issue? I am using the exact same Airtable schema/data as in the aec-startups Airtable.

**Comment by gtalarico** [comment]
Fixed a while back
