### ISSUE TITLE
Can't see any entries after "n"

### ISSUE THREAD

**Issue by theo-armour** [gtalarico/aec-startups#66]
List is being truncated after "nPlan"

![image](https://user-images.githubusercontent.com/547626/92319329-98d95180-efcb-11ea-9e03-beaba3c1e18b.png)

**Comment by gtalarico** [comment]
You are right - I will look into this tomorrow.

**Comment by gtalarico** [comment]
lambda was capping records to first 100.
fixed here:
https://github.com/gtalarico/aec-startups/commit/598c448c631a84f82cfa9c84e421456dd122c5ab

invalidated cache to fix should be fixed

nplan still shows last, not sure why, but at least all records seem to be coming through, including the W's.

![image](https://user-images.githubusercontent.com/9513968/93034965-98a30c80-f5f0-11ea-9c7e-3de94b14f6a6.png)

**Comment by theo-armour** [comment]
@gtalarico 

nPlan is probably last maybe because Linux sorts lower case letters after uppercase letters

Nonetheless, thanks for the fix!

**Comment by gtalarico** [comment]
ha! you are right about case but not linux, JS
https://github.com/gtalarico/aec-startups/blob/ef368c1872fafa199ba3b92c9a726e5d9b82a612/src/App.vue#L71

**Comment by theo-armour** [comment]
@gtalarico 

My doh!

What happens if you add `.toLowerCase()` to each of the titles?

**Comment by gtalarico** [comment]
it would fix it
