### ISSUE TITLE
Add Repo Image 

### ISSUE THREAD

**Issue by johnpierson** [gtalarico/aec-startups#9]
Could be nice to add an image to the repo that represents this resource when the URL unfurls. 
😁 
https://github.blog/2019-04-17-custom-open-graph-images-for-repositories/

**Comment by gtalarico** [comment]
nice touch

https://github.com/gtalarico/aec-startups/settings

**Comment by gtalarico** [comment]
![image](https://user-images.githubusercontent.com/9513968/57574224-d767f780-73e9-11e9-992b-e109aeff1a05.png)
